### ISSUE TITLE
On Windows Git Bash: athr.lib is "Program Files (x86)" not "Program Files" so Bgen build fails

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen#8]
On Windows, I got Git Bash re-installed and got cmake, zstd, zlib, and athr installed.
athr was installed with 
`curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere bash`
But athr went to "C:\Program Files (x86)\athr" instead of "C:\Program Files\athr", so 
` curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=bgen bash` failed.

A work around was to copy the athr directory to "C:\Program Files\athr"

**Comment by horta** [comment]
Weird. Have you checked whether the installed athr is indeed 64bits? Is your Windows 64 bits?

You can also set install prefix:

```
curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere INSTALL_PREFIX="/path/to/program/files" bash
```

**Comment by CarlKCarlK** [comment]
Here is confirmation that athr and Windows are 64 bit.
![64Annotation 2020-04-06 091753](https://user-images.githubusercontent.com/6549183/78580723-a6559a00-77e7-11ea-83d5-294629a82327.jpg)

**Comment by horta** [comment]
So it is a bug indeed. (Maybe cmake is 32 bits?) I'm installing Parallels here with Windows so I can debug those problems properly. Thanks a lot!

**Comment by horta** [comment]
Now I remember the problem: https://gitlab.kitware.com/cmake/cmake/issues/18312
Cmake sometimes decide to install 64-bits programs into "Program Files (x86)". They have not decided yet what to do with that, so I will just recommend always specifying the installation prefix, like I posted above.
